### ISSUE TITLE
Content Provider

### ISSUE THREAD

**Issue by Nafanya** [IFMO-MobDev-2014/lesson7#2]
Согласно документации, "...content providers are primarily intended to be used by other applications...", а так как в задании ничего не сказано о том, что этим content provider'ом кто-то (другое приложение) будет пользоваться,  я не вижу смысла в его использовании. Почему бы просто не воспользоваться базой данных ?

**Comment by thevery** [comment]
ContentProvider gives your much better lifecycle control and data access encapsulation plus cursor update/notify mechanism.

**Comment by pva701** [comment]
О каком жизненном цикле идет речь? С базой данных, кажется, все просто - она один раз создается, и ты пишешь в нее когда хочешь, какие проблемы с жизненным циклом?
Что имеется ввиду под data access encapsulation?

**Comment by thevery** [comment]
> О каком жизненном цикле идет речь?

Open/close/create/upgrade.

> Что имеется ввиду под data access encapsulation?

Single entry point for all database operations.
